spring.application.name=VoteAPI
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/vote-db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWD}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true